version: '3'

services:
    web:
        image: nginx:1.21.1-alpine
        volumes:
            - ./app:/usr/share/nginx/html
            - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - "php"
    php:
        build: ./docker-php
        volumes:
            - ./app:/usr/share/nginx/html
    db:
        image: mysql:5.7
        volumes:
            - ./docker-mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=bancoteste
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=danielmn
            - MYSQL_PASSWORD=123456
